# Generated by Django 6.0.2 on 2026-02-24 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active'), ('very_active', 'Very_active')], max_length=20)),
                ('goal', models.CharField(choices=[('lose_fat', 'Lose_fat'), ('maintain', 'Maintain'), ('gain_muscle', 'Gain_muscle')], max_length=20)),
                ('daily_calories', models.IntegerField(blank=True, null=True)),
                ('daily_protein', models.IntegerField(blank=True, null=True)),
                ('daily_carbs', models.IntegerField(blank=True, null=True)),
                ('daily_fat', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
